if print("Hello World!") then
print("Blox Fruits Loading...")
print("Blox Fruits Loaded...")
print("Choose Team")
print("Choosed Marines")
print("Pirate Starter Map")
print("Marine Starter Map")
print("Level: 1")
print("Level Max: 2675")
print("Ability: N/A")
print("Fighting Style: Combat")
print("Blox Fruit: N/A")
print("Sword: Katana")
print("Gun: N/A")
print("Bounty: 0")
print("Beli: 1000$")
print("Destroy(Blox)")
print("if Blox then Destroy() end")
print("Destroy()", "Destroyed")
print("if Destroyed then Destroy()")
print("random", "random", "random", "random")
print("TEST")
print("discord.gg/")
print("nothing")
print("end")
print("0")
print("Roblox: Blox Fruits")
print("Destroy()")
print("Destroyed()")
print("Kai Hub V69")
end
